### ISSUE TITLE
[Request] Documentation on adding zones manually

### ISSUE THREAD

**Issue by MacroPower** [steamcache/steamcache-dns#13]
I already have an operational DNS server, could you please include a list of domain names to forward to the steam cache server (either in the documentation here or on the other projects?) I am sure I can eventually parse it out from the docker files, but it would be much more convenient to just have a list of domains to forward in a readme.

Thanks!

**Comment by astrolox** [comment]
I agree we need better documentation.

The intention with this image is to make it so that you don't need the list of domains. 

You run this image, place it in front of your normal DNS server and all the hard work is done for you. By place in front I mean that your client computers send their queries to a running instance of this image, and this forwards requests it can't handle.

I can see value in publishing and maintaining a list of the domains which need to be overridden so you can do it without this image. I suspect that if we tried to do this, the list would unintentionally become out of date and out of sync with the config -and- I think no list is better than an old or incorrect list.

Please feel free to parse such a list out of our configuration if it is of use to you. Note that we have generated this through trial and error, although we think it's comprehensive, we can't guarantee it.
