### ISSUE TITLE
It's working with EA and Lol but steam do not cache :-)

### ISSUE THREAD

**Issue by madsjepsen0** [steamcache/steamcache-dns#9]
cool was tested with lol, ea, steam the caches ea and lol but steam does not work

**Comment by Robby12345** [comment]
I think the zone *.steamcontent.com is missing since the last PR. 

Look at the bind config before the merge https://github.com/steamcache/steamcache-dns/blob/6e643ddbe4c8f80630c385ee462a4f38df8f675b/overlay/etc/bind/steamcache.conf
And After: https://github.com/steamcache/steamcache-dns/blob/de807f1a1b5f42ccfeaaf4389535b074cfe9a736/overlay/etc/bind/cache.conf

**Comment by JasonRivers** [comment]
Commit cf19450 should fix this - I'm unable to fully test the DNS image right now due to lack fixed line internet. Let me know if there are any issues with it.

**Comment by madsjepsen0** [comment]
Having tested with steam and origin and it's working great
